// app/src/app/notfound/notfound.component.ts
// Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

import { Component } from '@angular/core';

@Component({
  selector: 'app-page-notfound',
  templateUrl: './notfound.component.html'
})
export class NotfoundComponent {}

<app-header-outside></app-header-outside>
<div class="wsl-min-h-screen-1 container mx-auto grid grid-cols-1 place-content-center">
  <div class="w-full md:max-w-screen-sm mx-auto flex flex-col items-center justify-center space-y-4">
    <div class="text-center">
      <h2 class="text-3xl font-medium">Page Not Found</h2>
      <h3 class="text-xl wsl-text-muted">Houston, we have a problem!</h3>
    </div>
    <img src="./assets/undraw/undraw_not_found_60pq.svg" class="px-8 py-4" />
    <p class="p-4 md:text-justify font-light">
      The page or document you requested is not accessible.
      This might be due that no such page or document exists or you
      have insufficient privileges to access it.
      If you think you are encountering this page by error, please
      <a href="/feedback">contact</a> your administrator.
    </p>
    <button type="button" routerLink="/" class="wsl-btn-light">
      Back to Home
    </button>
  </div>
</div>
<app-footer-outside></app-footer-outside>

// web/app/not-found.tsx
// Copyright 2022 Touca, Inc. Subject to Apache-2.0 License.

import { Metadata } from 'next';
import Link from 'next/link';
import React from 'react';

const content = {
  title: 'Page Not Found',
  subtitle: 'Did you make a typo?',
  description: `
    The page or document you requested is not accessible. Either it does not
    exist or you have insufficient privileges to access it. Let us know if
    you think you are encountering this page by error.`
};

export const metadata: Metadata = {
  title: content.title
};

export default function NotFound() {
  return (
    <section className="bg-gradient-to-b from-dark-blue-900 to-dark-blue-800">
      <div className="wsl-min-h-screen-1 container mx-auto grid place-content-center space-y-12 px-4">
        <div className="space-y-2 text-center">
          <h2 className="text-4xl font-light text-white">{content.title}</h2>
          <p className="text-xl text-white">{content.subtitle}</p>
        </div>
        <div className="mx-auto max-w-xl space-y-8 rounded-xl border border-dark-blue-700 bg-dark-blue-800 bg-opacity-50 p-8">
          <div className="">
            <p className="text-lg font-light text-white md:text-xl">
              {content.description}
            </p>
          </div>
          <div className="text-center">
            <Link
              href="/"
              className="rounded-xl border border-transparent bg-sky-900 bg-opacity-50 p-4 text-sm leading-6 text-gray-300 hover:border-sky-900 hover:text-white">
              Back to Main Page
            </Link>
          </div>
        </div>
      </div>
    </section>
  );
}
